### ISSUE TITLE
--demo fails under python3

### ISSUE THREAD

**Issue by avdd** [xolox/python-humanfriendly#28]
A couple of tiny python3 incompatibilities running `humanfriendly --demo`::
```
Traceback (most recent call last):
  File "./bin/humanfriendly", line 11, in <module>
    sys.exit(main())
  File "/b/lib/python3.6/site-packages/humanfriendly/cli.py", line 157, in main
    partial()
  File "/b/lib/python3.6/site-packages/humanfriendly/cli.py", line 244, in demonstrate_ansi_formatting
    ] for color_name in sorted(ANSI_COLOR_CODES.keys())
  File "/b/lib/python3.6/site-packages/humanfriendly/cli.py", line 244, in <listcomp>
    ] for color_name in sorted(ANSI_COLOR_CODES.keys())
  File "/b/lib/python3.6/site-packages/humanfriendly/cli.py", line 243, in <listcomp>
    ) for label, kw in intensities
TypeError: unsupported operand type(s) for +: 'dict_items' and 'list'
```

Fixing that then produces::
```
Traceback (most recent call last):
  File "./bin/humanfriendly", line 11, in <module>
    sys.exit(main())
  File "/b/lib/python3.6/site-packages/humanfriendly/cli.py", line 157, in main
    partial()
  File "/b/lib/python3.6/site-packages/humanfriendly/cli.py", line 251, in demonstrate_ansi_formatting
    demonstrate_256_colors(16, 231, '216 colors')
  File "/b/lib/python3.6/site-packages/humanfriendly/cli.py", line 274, in demonstrate_256_colors
    blocks = [colors[n:n + colors_per_line] for n in range(0, len(colors), colors_per_line)]
TypeError: 'float' object cannot be interpreted as an integer
```

A quick patch to fix::
```
--- /b/lib/python3.6/site-packages/humanfriendly/cli.py	2018-05-03 11:52:36.629392862 +1000
+++ ./cli.py	2018-05-03 11:51:53.161390713 +1000
@@ -242 +242 @@
-                    **dict(kw.items() + [(color_type, color_name)])
+                    **dict(list(kw.items()) + [(color_type, color_name)])
@@ -272 +272 @@
-        colors_per_line = columns / width
+        colors_per_line = int(columns / width)
```

Cheers.

**Comment by xolox** [comment]
Thanks for the bug report and suggested changes @avdd! This is fixed in [release 4.12.1](https://humanfriendly.readthedocs.io/en/latest/changelog.html#release-4-12-1-2018-05-10) which is now available on GitHub and PyPI.
